---
title: "Obtendo dados do Ipeadata via API"
format:
  gfm: default
  pdf:
    pdf-engine: pdflatex
    header-includes: 
    - \usepackage{fvextra}
    - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}, fontsize=\small}
  
    - \usepackage{tcolorbox}
    - \newtcolorbox{functioncard}{
        colback=red!5,
        colframe=red!70!black,
        arc=2mm,
        boxrule=0.8pt}
  html:
    css: stylesheet.css
    
editor: source
---

## Extraindo os dados

<p>
|       Este tutorial visa auxiliar pesquisadores a coletar bases de dados do Ipeadata disponíveis em sua API. Em sua essência, este repositório possui três scripts principais: **ipeadata_query**^[https://github.com/paulo-icaro/Ipeadata_API/blob/main/Ipeadata_Query.R], **ipeadata_url**^[https://github.com/paulo-icaro/Ipeadata_API/blob/main/Ipeadata_URL.R] e **ipeadata_aapi**^[https://github.com/paulo-icaro/Ipeadata_API/blob/main/Ipeadata_API.R]. As duas últimas funções atuam em conjunto como a engrenagem para obtenção das bases de dados. Se por um lado **ipeadata_url** atua na criação das URLs onde os dados estão localizados, por outro **Ipeadata_API** é responsável por extrair a informação lá localizada. Por fim, a função **Ipeadata_Query** combina estas duas funções em uma única interface, tornando simples o processo de extração de dados.

{{< include includes/ipeadata_query.qmd >}}

|       Os argumentos da função **Ipeadata_Query** são:
* ipeadata_series_code: codigo das séries a serem extraidas.
* ipeadata_series_name: nome das séries a serem extraidas.
* time_interval: período^[Certamente, existem diversas bases de dados com diferentes frequências. No entanto, para uma extração padronizada o código somente irá filtrar os dados baseado no ano da série.] (ano) correspondente ao dado a ser extraído.
* source_github: Este argumento é opcional e permite ao pesquisador escolher acessar a função diretamente deste diretório ou de uma cópia das funções disponíveis em sua máquina local.

|       Vejamos um exemplo. Suponha que desejamos coletar os dados referente ao Índice de Preços (IPCA) e ao PIB brasileiro no período 2015-2025. Enquanto a série de preços possui frequência mensal, o PIB possui frequência anual.
</p>

```{r Tutorial, echo = TRUE, warning = FALSE, message = FALSE, eval = TRUE, comment = ''}
# ======================= #
# === Data Extraction === #
# ======================= #

# --- Ipeadata Query Function --- #
source('https://raw.githubusercontent.com/paulo-icaro/Ipeadata_API/refs/heads/main/Ipeadata_Query.R')

# --- Previous Info --- #
series_code = c('PRECOS12_IPCA12', 'WEO_PIBWEOBRA')
series_name = c('br_price_index', 'br_gdp')
period = as.character(x = 2015:2025)


database = ipeadata_query(series_code, series_name, period)
print(head(database, 15), row.names = FALSE)
```

<p>
|       O fato das duas séries terem frequências temporais diferentes implica em um conjunto de dados desigual. Esse ponto, contudo, não será um problema desde que alguns cuidados sejam tomados. Neste exemplo, a base de dados final possui 131 observações mensais e 10 observações anuais, cada uma correspondendo ao primeiro mês de cada ano. Nessas circunstâncias, não haverá problema em razão de que todos os dados foram acessados.
|       Entretanto, caso a ordem de especificação das variáveis estivesse invertida (PIB e IPCA), teríamos um problema considerável. Nesse caso, o conjunto de dados final teria somente 10 observações no total, onde somente a primeira observação mensal de cada ano seria aproveitada para o caso da série de preços.

|       Dessa maneira duas soluções para contornar o problema surgem:
* Ao informar as séries a serem coletadas, a ordem de definição das variáveis devem sempre ser feita de modo que as séries de alta-frequência sejam sempre priorizadas.
* Importar séries juntas de acordo com sua frequência temporal. Nessa alternativa será necessário utilizar a função **Ipeadata_Query** mais de uma vez.
</p>